### ISSUE TITLE
Support for IPv6

### ISSUE THREAD

**Issue by avadhanij** [michaelrigart/ansible-role-interfaces#37]
I see that listing an IPv6 address for an interface is currently not supported. Any plans of supporting it?

**Comment by markgoddard** [comment]
I remember @jpds wanting to do this. Did you get anywhere with it?

**Comment by avadhanij** [comment]
#39

**Comment by avadhanij** [comment]
@markgoddard ... It appears that the ansible-galaxy role hasn't been updated. Can you republish?

**Comment by markgoddard** [comment]
Done. Odd that the import has not worked - the travis config looks ok.

**Comment by avadhanij** [comment]
Nope, it's still not getting the latest. Perhaps the version has to be changed? Kind of similar to python packages?

**Comment by markgoddard** [comment]
Correct - we started tagging this repo in February and now have to create a new tag in order for the changes to be published on galaxy. I've just tagged v1.1.0.

You can always reference the git repo and a specific branch in a galaxy requirements file if necessary.
